#!/usr/bin/env bash

# -----------------------------------------------------
# Helper functions
# -----------------------------------------------------

function check_stack_context {
  if [[ -z "${RABBITMQ_DEFAULT_USER:-}" || -z "${RABBITMQ_DEFAULT_PASS:-}" ]]; then
    log_error "RabbitMQ default credentials missing from 'secrets.env'."
    exit 1
  fi
}

function build_secrets {
  if [[ ! -f "$SECRETS/ca.crt" || ! -f "$SECRETS/ca.key" ]]; then
    make-ca rabbitmq -o "$SECRETS"
    make-truststore rabbitmq "$SECRETS/ca.crt" -o "$SECRETS"
  fi
  
  if [[ ! -f "$SECRETS/rabbitmq.crt" || ! -f "$SECRETS/rabbitmq.key" ]]; then
    make-cert rabbitmq "$BROKER_NODES $BROKER_FQDN_NODES" -o "$SECRETS" --ca-crt "$SECRETS/ca.crt" --ca-key "$SECRETS/ca.key"
  fi
}

# -----------------------------------------------------
# Commands
# -----------------------------------------------------

function command_rabbitmq_install_plugins {
  discover_stack_context
  run_rabbitmq_install_plugins
}

# -----------------------------------------------------
# RabbitMQ functions
# -----------------------------------------------------

function run_rabbitmq_install_plugins {
  local container_id

  container_id=$(docker -H "ssh://$BROKER" ps --filter "name=${STACK}_broker" --filter status=running -q)
  docker -H "ssh://$BROKER" exec "$container_id" rabbitmq-plugins enable rabbitmq_prometheus
}

# -----------------------------------------------------
# Stack functions
# -----------------------------------------------------

function stack_check_env {
  if [[ ! -d "$CONFIGS" || ! -d "$SECRETS" ]]; then
    log_error "Secrets directory is missing from '$ENVIRONMENT_BASE'."
    exit 1
  fi
}

function stack_discover {
  export BROKER=$(first "$BROKER_FQDN_NODES")  # For tooling
  export BROKER_REPLICAS=$(count "$BROKER_NODES")
}

function stack_tools {
  local tool="$STACK_PATH/tools/$1"
  shift

  if [[ ! -x "$tool" ]]; then
    log_error "$tool doesn't exist or isn't executable."
    exit 1
  fi

  log_info "Running $tool with args: $*"
  "$tool" "$@"
}

function stack_env {
  echo
  echo "DOCKER IMAGE       = $RABBITMQ_IMAGE"
  echo "BROKER NODES       = ($BROKER_REPLICAS)"
  list "$BROKER_NODES"
  echo
  echo "BROKER TLS PORT    = $RABBITMQ_BROKER_TLS_PORT"
  echo "MANAGEMENT PORT    = $RABBITMQ_MANAGEMENT_PORT"
  echo
}

function stack_deploy {
  check_stack_context
  build_secrets
  docker stack deploy --detach=true -c rabbitmq.yml "$STACK"

  log_info "Waiting for RabbitMQ to become healthy..."
  until curl --cacert "$SECRETS/ca.crt" -fsS "https://$BROKER:$RABBITMQ_MANAGEMENT_PORT/api/health/checks/is-in-service" >/dev/null 2>&1; do
    sleep 5
  done

  run_rabbitmq_install_plugins
}
